### ISSUE TITLE
QR code not generate 

### ISSUE THREAD

**Issue by tylerhindi1** [ravindu01manoj/Sew-Queen#31]
I am trying to generate QR code but it's not generating. I run script on replit and termux app but both time show me errors
Please fix it

**Comment by ravindu01manoj** [comment]
multi-device version comming soon... wait for it :)

**Comment by tylerhindi1** [comment]
Please update ASAP . I want to test your bot

**Comment by lopinhghj** [comment]
I am trying to create your bot, but it ban my account in Heroko, why? (Knowing that my country is Spain)

**Comment by ravindu01manoj** [comment]
> I am trying to create your bot, but it ban my account in Heroko, why? (Knowing that my country is Spain)

I will Fix it with next version

**Comment by lopinhghj** [comment]
> 

Well, thank you very much and thank you for your humility.

**Comment by lopinhghj** [comment]
I hope you add a game X O

**Comment by ishansandeepa20040709** [comment]
අනේ රවිදූ අයියේ ටග්ගාලා ඕක හදන්නකෝ මට නම් ඉවසිල්ලක් නැ .......... අර girl වොයිස් ටික නම් අනිව ඕන හොදේ ........     ඔයාට බුදු සරණයි .
තවත් දියුණු වෙන්න කියලා ප්‍රාර්තනා කරනවා ...

**Comment by ChamodKeshan** [comment]
**Qr code not support normally whatsapp**
**you can fix this?**

**Comment by ravindu01manoj** [comment]
> **Qr code not support normally whatsapp** **you can fix this?**

this project was closed
